name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'  # Set this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Authenticate with Google Cloud
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Deploy to Google Cloud Functions
      run: |
        gcloud functions deploy WebServer-ContractAid \
          --entry-point=helloHttp \
          --runtime=nodejs20 \  #this to your Node.js version
          --trigger-http \
          --allow-unauthenticated  # Remove this flag to restrict access

